### PR TITLE
Added support for [*] and [#] tags

### PR DESCRIPTION
**Pull request by c-p-b**

### CODE REVIEW

**Comment by ackwell** [comment]
Aww man, I totally forgot I'd not done this.

Travis is reporting a fail - looks like the last character of the first list item is being skipped. Once that's fixed up, I'll merge it ASAP.

Thanks!

**Comment by c-p-b** [comment]
Whoops! Mocha passed on my end. Looks like a discrepancy in the newline handling. I'll throw up a fix ASAP

**Comment by c-p-b** [comment]
Fixed! I wasn't accounting for Windows \r\n vs. Unix \n (http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html) I also made the code a bit more elegant and added some fancy regex to do the dirty work to keep more in line with your patterns. Looks like the CI build is passing now. Merge away!

**Comment by ackwell** [comment]
Ah, of course - that'd do it!

Excellent work, many thanks.

**Pull request merged**
